filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          matchers:
            - logs_path:
                logs_path: '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://10.9.21.8:8070"]
  protocol: "http"
  username: "elastic"
  password: "changeme"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
