---

- name: replace nginx.conf
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/nginx.conf"

- name: replace default.conf
  template:
    src: templates/default.conf
    dest: "/etc/nginx/conf.d/default.conf"

- name: check nginx configs
  shell: "/usr/sbin/nginx -t"

- name: restart nginx
  systemd:
    state: restarted
    name: nginx
