#cloud-config
ca_certs:
  trusted:
  - |
   -----BEGIN CERTIFICATE-----
   mcIfeg7jLQitChws/zyrVQ4PkX4268NXSb7hLi18YIvDQVETI53O9zJrlAGomecs
   -----END CERTIFICATE-----
  - |
   -----BEGIN CERTIFICATE-----
   MIIEsDCCA5igAwIBAgIQd70OB0LV2enQSdd00CpvmjANBgkqhkiG9w0BAQsFADBM
   -----END CERTIFICATE-----
  - |
   -----BEGIN CERTIFICATE-----
   dHA6Ly9vY3NwLmdsb2JhbHNpZ24uY29tL2dzZ2NjcjNkdnRsc2NhMjAyMDBWBgNV
   -----END CERTIFICATE-----
timezone: Europe/Moscow
ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - ntp.local
apt:
  primary:
    - arches: [default]
      uri: https://mirror.local/repository/apt-proxy/
package_update: true
package_upgrade: true
packages:
  - ansible
  - git
  - net-tools
  - open-vm-tools
  - resolvconf
  - vim
users:
  - default
  - name: ansible
    shell: /bin/bash
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: <passwd>
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB...
runcmd:
  - sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
  - systemctl restart ssh
write_files:
- path: /etc/docker/daemon.json
  owner: root:root
  content: |
    {
      "registry-mirrors" : ["https://mirror.local"],
      "insecure-registries" : ["mirror.local"]
    }
