#cloud-config
ca_certs:
  trusted:
  - |
   -----BEGIN CERTIFICATE-----
   MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G
   -----END CERTIFICATE-----
  - |
   -----BEGIN CERTIFICATE-----
   MIIEsDCCA5igAwIBAgIQd70OB0LV2enQSdd00CpvmjANBgkqhkiG9w0BAQsFADBM
   -----END CERTIFICATE-----
  - |
   -----BEGIN CERTIFICATE-----
   MIIHejCCBmKgAwIBAgIMczPnlDpmWFWJnok8MA0GCSqGSIb3DQEBCwUAMFMxCzAJ
   -----END CERTIFICATE-----
timezone: Europe/Moscow
ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - ntp.local
apt:
  primary:
    - arches: [default]
      uri: https://mirror.local/repository/apt-proxy/
package_update: true
package_upgrade: true
packages:
  - ansible
  - git
  - net-tools
  - open-vm-tools
  - resolvconf
  - vim
users:
  - default
  - name: ansible
    shell: /bin/bash
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: <passwd>
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAA...
write_files:
- path: /etc/sysctl.d/60-arp-ignore-ipv4.conf
  owner: root:root
  content: |
    net.ipv4.conf.all.arp_ignore=1
    net.ipv4.conf.all.arp_announce=2
- path: /etc/docker/daemon.json
  owner: root:root
  content: |
    {
      "registry-mirrors" : ["https://mirror.local"],
      "insecure-registries" : ["mirror.local"]
    }
runcmd:
  - sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
  - systemctl restart ssh
  - sysctl -w net.ipv4.conf.all.arp_ignore=1
  - sysctl -w net.ipv4.conf.all.arp_announce=2
