# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vagrant" do |vagrant|
    vagrant.vm.box = "centos/7"
    vagrant.vm.hostname = "vagrant"
    vagrant.vm.provider "virtualbox"
    vagrant.ssh.username = "vagrant"

    vagrant.vm.network "forwarded_port", guest: 8080, host: 8080

    vagrant.vm.provision :ansible do |ansible|
      ansible.playbook = "haproxy_install.yml"
      ansible.inventory_path = "inventory.yml"
    end

  end
end
