- name: create image from os disk
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: create image from os disk
      azure_rm_image:
        resource_group: resource_group
        name: image-test-comp
        os_type: Linux
        source:
          type: disks
          resource_group: resource_group
          name: disk-os-test-comp
