version: '2'

services:

  elasticsearch:
    image: innodockerregistry.azurecr.io/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "10.9.21.8:8070:9200"
      - "10.9.21.8:8050:9300"

  kibana:
    image: innodockerregistry.azurecr.io/kibana:7.6.0
    container_name: kibana
    environment:
      SERVERNAME: kibana
      SERVER_SSL_ENABLED: "false"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_HOSTS: "http://10.9.21.8:8070"
      ELASTICSEARCH_URL: "http://10.9.21.8:8070"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "10.9.21.8:8060:5601"
